### ISSUE TITLE
使用SqlServer报错

### ISSUE THREAD

**Issue by zicanli** [jellydong/LJDAPP#1]
是不是还不能完全使用SqlServer，我转到SqlServer看到错误，发现PermissionManage和CurrentUserManage使用的是MySql,还有就是大佬能不能给点初始数据

**Comment by jellydong** [comment]
> 是不是还不能完全使用SqlServer，我转到SqlServer看到错误，发现PermissionManage和CurrentUserManage使用的是MySql,还有就是大佬能不能给点初始数据

数据库已经加上了，一开始忘了上传。可以完全使用，把那些SQL改成SQL　Server的就可以了

**Comment by jellydong** [comment]
> 是不是还不能完全使用SqlServer，我转到SqlServer看到错误，发现PermissionManage和CurrentUserManage使用的是MySql,还有就是大佬能不能给点初始数据

数据库ljdapp.sql
