### ISSUE TITLE
创建数据库脚本以及sql server 支持

### ISSUE THREAD

**Issue by Kunsai** [jellydong/LJDAPP#2]
您好，请提供寸创新数据库脚本好吗？另外，用options.UseSqlServer连接sql server 数据库出错，请测试。

**Comment by Kunsai** [comment]
非常不错的项目！望回复

**Comment by Kunsai** [comment]
权限控制，菜单的权限控制有问题，花了一天时间搞定了

**Comment by jellydong** [comment]
> 您好，请提供寸创新数据库脚本好吗？另外，用options.UseSqlServer连接sql server 数据库出错，请测试。

可以使用SqlServer，我就是服务器配置低所以换成了MySql，需要修改自己写的SQL的地方。

**Comment by jellydong** [comment]
> 权限控制，菜单的权限控制有问题，花了一天时间搞定了

什么问题？

**Comment by Kunsai** [comment]
创建一个新菜单，然后分配权限时是有问题的，不知道是不是我自己添加的数据问题，你可以测试一下。

**Comment by jellydong** [comment]
> 创建一个新菜单，然后分配权限时是有问题的，不知道是不是我自己添加的数据问题，你可以测试一下。

抱歉，最近工作忙，已经上传~ljdapp.sql
